name: Lint

on: pull_request

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: borales/actions-yarn@v3.0.0
      - run: yarn lint
